name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [self-hosted]
    steps:
      - name: venv
        run: python -m venv venv
      - name: venv activate
        run: source venv/bin/activate
      - name: flake8
        run: pip install flake8
      - name: Run linters
        run: flake8 ./mlops/features.py

